# Celery configuration
CELERY_BROKER_URL: redis://localhost:6379/0
CELERY_RESULT_BACKEND: redis://localhost:6379/0

SECRET_KEY: VXy2nnUkuBZJOQysIqzN6QsU4XCmeQqE
SQLALCHEMY_DATABASE_URI: "mysql+mysqlconnector://root:xiaoyezi.xyz@10.3.2.51/boneage?charset=utf8mb4"
